### ISSUE TITLE
Support password protected videos

### ISSUE THREAD

**Issue by GiorgioUghini** [sup3rgiu/PoliWebex#1]
Sometimes it happens that the video is password protected by the instructor. As an example, this is the case of the first video of the "Misure" course.

Link to video: [Misure - Lecture 1](https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/play/c52bd32aab374983878102690d02031c)
Password of the video: `misure`

After the webpoliself login flow, the user is redirected on a page where it is mandatory to insert the password for the video, otherwise no access is granted (and thus the PoliWebex tool won't work).

Input element xpath: `//*[@id="main_content"]/div/div/div[2]/div/div[1]/input`
Submit button xpath: `//*[@id="main_content"]/div/div/div[2]/button`

Thank you for your always useful and fast work ;)

EDIT: Attach image
![Image](https://i.imgur.com/r7B810D.png)

**Comment by sup3rgiu** [comment]
Support added in https://github.com/sup3rgiu/PoliWebex/commit/74296e47007a2d922e48cc2990ba02c84210f57d
