### ISSUE TITLE
'taskkill' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Biumsp** [sup3rgiu/PoliWebex#14]
Trying to download some videos I get this error. 

![00000000000000000000000](https://user-images.githubusercontent.com/78282465/108908289-6b3c9f00-7623-11eb-94cc-fdfc8e3683ac.jpg)

It used to work well some months ago.
Can anyone help me?

**Comment by sup3rgiu** [comment]
If you type in CMD `where taskkill` what do you get?

**Comment by Biumsp** [comment]
I get an error:
'where' is not recognized as an internal or esternal command

**Comment by sup3rgiu** [comment]
That's really weird.

Please check manually if you have these files:

`C:\Windows\System32\taskkill.exe`
`C:\Windows\System32\where.exe`

**Comment by Biumsp** [comment]
Yes, I have both of them.

**Comment by sup3rgiu** [comment]
Check if you have `C:\Windows\System32` in the `Path` under Environment Variables

**Comment by Biumsp** [comment]
It wasn't in the path (not sure how it happened) and that solved the problem! 
Thanks a lot!
