### ISSUE TITLE
Can't get current video XML-URL. Going to the next one.

### ISSUE THREAD

**Issue by Rubenxx00** [sup3rgiu/PoliWebex#17]
Hello,
I get this error with every recording link I've tried:

**Can't get current video XML-URL. Going to the next one.**

Maybe Webex API changed?

**Comment by sup3rgiu** [comment]
Should be fixed in https://github.com/sup3rgiu/PoliWebex/commit/9e07ee177ae6a6fb7e9b407fbd3802a2321166e3

**Comment by sup3rgiu** [comment]
Closed for inactivity
