### ISSUE TITLE
Add support for 2FA login

### ISSUE THREAD

**Issue by barondem** [sup3rgiu/PoliWebex#19]
Starting from 2nd November, it is now mandatory to authenticate with a 2FA authentication method such as SPID or CIE, so for the application to continue working it is necessary to implement a mechanism to handle this. I suppose that it could be easier to switch back to a non-headless authentication, at least initially, since the authentication with SPID also requires to choose the SPID provider (though, it could be probably done in a headless way later on).

**Comment by 1alessandro1** [comment]
I think this can be closed, since @sup3rgiu added support for 2FA logins recently
