### ISSUE TITLE
Incorrect name in notifications

### ISSUE THREAD

**Issue by Raif9** [sup3rgiu/PoliWebex#2]
![Screenshot (55)](https://user-images.githubusercontent.com/62006861/93269728-e44fe480-f7af-11ea-80aa-138602640154.png)

**Comment by sup3rgiu** [comment]
Wooop, fixed in https://github.com/sup3rgiu/PoliWebex/commit/202936c6256750f0bdc6b51998b908d3bb4dfdbf
