### ISSUE TITLE
Problema download registrazione

### ISSUE THREAD

**Issue by TeddyPoliMi** [sup3rgiu/PoliWebex#4]
Ciao, scusa il disturbo ma provando a scaricare una registrazione mi compare questo messaggio di errore

"Reusing password saved in system's keychain!

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to WebEx login page...
Filling in Servizi Online login form...
(node:3648) UnhandledPromiseRejectionWarning: TimeoutError: waiting for target failed: timeout 90000ms exceeded
    at Function.waitWithTimeout (C:\Projects\PoliWebex\node_modules\puppeteer\lib\helper.js:228:26)
    at Browser.waitForTarget (C:\Projects\PoliWebex\node_modules\puppeteer\lib\Browser.js:214:27)
    at Browser.<anonymous> (C:\Projects\PoliWebex\node_modules\puppeteer\lib\helper.js:112:23)
    at login (C:\Projects\PoliWebex\poliwebex.js:274:19)
(node:3648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

Con PoliDown non ho mai avuto problemi e per questo mi sono limitato a seguire le istruzioni date qua
Pensi di sapere qual è il problema?

**Comment by sup3rgiu** [comment]
Ciao, prova a scaricare la nuova versione pubblicata poco fa e poi prova ad aggiungere al comando il flag `-i 2`.
In questo modo verrà raddoppiato il valore dei timeout (puoi mettere anche valori decimali)
Fammi sapere

**Comment by sup3rgiu** [comment]
Il problema probabilmente era che veniva richiesto di scegliere la matricola desiderata dopo il login sui servizi online, e ciò non veniva gestito da PoliWebex.
Ho implementato anche la gestione di questo dettaglio. Prova la nuova versione

**Comment by sup3rgiu** [comment]
I'm closing this issue because it has been inactive for a few months

**Comment by benbars** [comment]
Ciao sup3rgiu, mi vedo anch'io costretto a disturbarti dopo molti tentativi (falliti) di risolvere lo stesso problema di @TeddyPoliMi . 

La situazione è quasi identica: con PoliDown una meraviglia (btw, lavoro grandioso), mentre con PoliWebex, pur seguendo rigorosamente i passaggi di installazione due volte, sembra ci siano sempre problemi al login. Non sapendo bene dove sbattere la testa, ho reinstallato nuovamente e ho anche provato la versione con GUI (PoliDL): non credevo c'entrasse molto ma ho provato lo stesso. 

Un'altra differenza rispetto al tutorial e alle istruzioni lette nei documenti della repo è la versione di ffmpeg, che è stata aggiornata di recente. Ho pensato di allegare alcuni screeshot per spiegarmi meglio. Nel caso volessi altre informazioni, contattami pure e farò il mio meglio. 

![vistaPoliDL](https://user-images.githubusercontent.com/79929054/109682098-64abab80-7b7e-11eb-95a4-f0d8534fa35b.png)
![vistaTerminale](https://user-images.githubusercontent.com/79929054/109682105-65444200-7b7e-11eb-8f32-c769a75b3286.jpg)


Qualche idea su quale potrebbe essere il problema? 

Ringraziandoti per il tuo lavoro, 

A presto

**Comment by sup3rgiu** [comment]
Ciao. Scrivimi su Telegram @sup3rgiu così provo aiutarti in maniera più veloce.

**Comment by benbars** [comment]
Ciao sup3rgiu, sì senz'altro! 

Scrivo subito grazie!
