### ISSUE TITLE
Insert argument for adding video password

### ISSUE THREAD

**Issue by controltheorist86** [sup3rgiu/PoliWebex#5]
Ciao,
ci sono video che richiedono, se aperti direttamente dal browser, una password impostata dal docente.

Servirebbe che il poliwebex intercetti questo campo e chieda la password altrimenti compare questo errore:

_(node:35421) UnhandledPromiseRejectionWarning: ReferenceError: errorMsg is not defined
    at downloadVideo (/Users/mac/Downloads/PoliWebex-master/poliwebex.js:139:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:35421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35421) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

e il video non viene scaricato.

**Comment by sup3rgiu** [comment]
Ciao! Questa funzione è stata implementata in una delle ultime commit.
Assicurati di avere il progetto aggiornato e poi potrai aggiungere il parametro `-w PASSWORD`

**Comment by controltheorist86** [comment]
Grazie ho provato  ma la stringa di comando, vista la password con caratteri speciali ritorna:

-bash: !@#": event not found.

Questo perché nella password sono stati inseriti alla fine caratteri speciali !@#

Ho utilizzato la seguente stringa:

node poliwebex --videoPwd "passwordconcaratterispeciali" --videoUrls  "linkalvideowebex"

**Comment by sup3rgiu** [comment]
Quello dipende dal terminale che stai usando.
Prova a mettere la password tra apici singoli
`-w 'passwordconcaratterispeciali'`

**Comment by controltheorist86** [comment]
Grazie. Funziona. Chiudo il thread.
