### ISSUE TITLE
Multiple errors during download

### ISSUE THREAD

**Issue by DaitiDay** [sup3rgiu/PoliWebex#8]
During the download of any WebEx recording I get 5 to 10 errors (with or without the -s flag) resulting in the video not being downloaded. Furthermore each time I restart the download the sequences reporting "download aborted" change "randomly". Tested on 2 different videos with the same result. Any idea on how to fix this and/or what might be the cause?

**Comment by sup3rgiu** [comment]
Can you post the errors log?

**Comment by DaitiDay** [comment]
Are you talking about the poliwebex output or the aria2c log? Cause I don't see any log file.
```
10/10 16:02:52 [ERROR] CUID#207 - Download aborted. URI=https://nln1vss.webex.com/hls-vod/recordingDir/QUhTSwAAAAQnV4O0SvuBnPDzOF5ez3rFknPzmna4OZy8lrMRpVZbtEz-FQCdr0A3p2z7IdL9_69X9_ubvJWibwPDWbOYZTmdU5nltbD-73TQqET3Fw8Jj5OB4kpePZU9gvTcGDFVR6kx1HHbJLTyFtlrI84cLkNGTGJWcCoRQue9IOPo0Fmw27UHUA4TLN-kAcZ4glwyshkJOgJwesgzwkrBUg5LX0ol0/timestamp/1602338132075/token/QUhTSwAAAASKj3S8ap1p7bOkySG3Bh92vzhCQAbDLV4X1-16cn9qWNFOrfIZmK3uGnSWAKVgxKJ1SmOhPRhByepbvSGiZ94fP_Hq8DesbcTHOhNVxmMQPodjMdFZG8oUNvCjZJ7Gk8BZNaKw4jeSAEj43vqVR3NcvcvED6smXGhP9urrlHVmliJpgLe-1_06J3unDn6poXUuH3f9xvScqc6l9tU8JOi8wnd7UwJRcbUnyUXLY2uDBtBFjZr8Mq2OlWYFaDx3iq29rdgJRZTGg2tdtAGsTSfi_DjAYUE16SUhtFM4ISDVRdt5BO5AuVgRXzdaa7q55uGW-jqe5H_Sg8iYlojWwx2yw9QlwC2o2BUhyd-anTYt399D-dc9K0CR2I-VdpNp8Sg1/fileName/merge_0_9359640.mp4Frag196Num196.ts
Exception: [AbstractCommand.cc:351] errorCode=8 URI=https://nln1vss.webex.com/hls-vod/recordingDir/QUhTSwAAAAQnV4O0SvuBnPDzOF5ez3rFknPzmna4OZy8lrMRpVZbtEz-FQCdr0A3p2z7IdL9_69X9_ubvJWibwPDWbOYZTmdU5nltbD-73TQqET3Fw8Jj5OB4kpePZU9gvTcGDFVR6kx1HHbJLTyFtlrI84cLkNGTGJWcCoRQue9IOPo0Fmw27UHUA4TLN-kAcZ4glwyshkJOgJwesgzwkrBUg5LX0ol0/timestamp/1602338132075/token/QUhTSwAAAASKj3S8ap1p7bOkySG3Bh92vzhCQAbDLV4X1-16cn9qWNFOrfIZmK3uGnSWAKVgxKJ1SmOhPRhByepbvSGiZ94fP_Hq8DesbcTHOhNVxmMQPodjMdFZG8oUNvCjZJ7Gk8BZNaKw4jeSAEj43vqVR3NcvcvED6smXGhP9urrlHVmliJpgLe-1_06J3unDn6poXUuH3f9xvScqc6l9tU8JOi8wnd7UwJRcbUnyUXLY2uDBtBFjZr8Mq2OlWYFaDx3iq29rdgJRZTGg2tdtAGsTSfi_DjAYUE16SUhtFM4ISDVRdt5BO5AuVgRXzdaa7q55uGW-jqe5H_Sg8iYlojWwx2yw9QlwC2o2BUhyd-anTYt399D-dc9K0CR2I-VdpNp8Sg1/fileName/merge_0_9359640.mp4Frag196Num196.ts
  -> [HttpResponse.cc:81] errorCode=8 Invalid range header. Request: 614223-656307/656308, Response: 0-656307/656308
```
This is an example out of the poliwebex.js output.

**Comment by sup3rgiu** [comment]
Yes sorry, I meant the aria2c log.

That `errorCode=8 Invalid range header` is a really strange error and I can find only few report of it on internet (seems related to an aria2c bug).

I've just tried downloading the .mp4 version of the video you are trying ton download and I've got no problems.

Can you try to insert this command in a terminal window and see if the error occurs again?

`aria2c -j 16 -x 16 "https://nln1vss.webex.com/apis/download.do?recordingDir=QUhTSwAAAAQnV4O0SvuBnPDzOF5ez3rFknPzmna4OZy8lrMRpVZbtEz-FQCdr0A3p2z7IdL9_69X9_ubvJWibwPDWbOYZTmdU5nltbD-73TQqET3Fw8Jj5OB4kpePZU9gvTcGDFVR6kx1HHbJLTyFtlrI84cLkNGTGJWcCoRQue9IOPo0Fmw27UHUA4TLN-kAcZ4glwyshkJOgJwesgzwkrBUg5LX0ol0&timestamp=1602338132075&token=QUhTSwAAAASKj3S8ap1p7bOkySG3Bh92vzhCQAbDLV4X1-16cn9qWNFOrfIZmK3uGnSWAKVgxKJ1SmOhPRhByepbvSGiZ94fP_Hq8DesbcTHOhNVxmMQPodjMdFZG8oUNvCjZJ7Gk8BZNaKw4jeSAEj43vqVR3NcvcvED6smXGhP9urrlHVmliJpgLe-1_06J3unDn6poXUuH3f9xvScqc6l9tU8JOi8wnd7UwJRcbUnyUXLY2uDBtBFjZr8Mq2OlWYFaDx3iq29rdgJRZTGg2tdtAGsTSfi_DjAYUE16SUhtFM4ISDVRdt5BO5AuVgRXzdaa7q55uGW-jqe5H_Sg8iYlojWwx2yw9QlwC2o2BUhyd-anTYt399D-dc9K0CR2I-VdpNp8Sg1&fileName=merge_0_9359640.mp4"`

And if you got the error, try this:

`aria2c "https://nln1vss.webex.com/apis/download.do?recordingDir=QUhTSwAAAAQnV4O0SvuBnPDzOF5ez3rFknPzmna4OZy8lrMRpVZbtEz-FQCdr0A3p2z7IdL9_69X9_ubvJWibwPDWbOYZTmdU5nltbD-73TQqET3Fw8Jj5OB4kpePZU9gvTcGDFVR6kx1HHbJLTyFtlrI84cLkNGTGJWcCoRQue9IOPo0Fmw27UHUA4TLN-kAcZ4glwyshkJOgJwesgzwkrBUg5LX0ol0&timestamp=1602338132075&token=QUhTSwAAAASKj3S8ap1p7bOkySG3Bh92vzhCQAbDLV4X1-16cn9qWNFOrfIZmK3uGnSWAKVgxKJ1SmOhPRhByepbvSGiZ94fP_Hq8DesbcTHOhNVxmMQPodjMdFZG8oUNvCjZJ7Gk8BZNaKw4jeSAEj43vqVR3NcvcvED6smXGhP9urrlHVmliJpgLe-1_06J3unDn6poXUuH3f9xvScqc6l9tU8JOi8wnd7UwJRcbUnyUXLY2uDBtBFjZr8Mq2OlWYFaDx3iq29rdgJRZTGg2tdtAGsTSfi_DjAYUE16SUhtFM4ISDVRdt5BO5AuVgRXzdaa7q55uGW-jqe5H_Sg8iYlojWwx2yw9QlwC2o2BUhyd-anTYt399D-dc9K0CR2I-VdpNp8Sg1&fileName=merge_0_9359640.mp4"`

**Comment by DaitiDay** [comment]
The first command did it. No errors reported and the video has been downloaded without any issues.

**Comment by sup3rgiu** [comment]
Well it is really weird since it's exactly the same command that PoliWebex uses.

The only thing that I can suggest right now is to try again (without the `-s` flag) and/or try on a different machine.

If you still not able to download videos, you can have a look at the browser extension: https://github.com/jacopo-j/WebXDownloader

**Comment by DaitiDay** [comment]
Where did you get that url for the video?

**Comment by sup3rgiu** [comment]
PoliWebex generates it.

In that case I crafted it manually from the informations posted in your log

**Comment by DaitiDay** [comment]
Can you explain the procedure? That way I can kinda solve the problem (not in the "right" way, but still its a solution)
Nevermind I think I got it

**Comment by sup3rgiu** [comment]
It's not that easy to manually generate and basically explaining the process would mean explaining the project, so you can check out the source code if you want.

 But if your ultimate goal is to find a way to download the videos, no matter what, I suggest you again to use this: https://github.com/jacopo-j/WebXDownloader
